GAME_DATE = "20180929"
GAME_NO = "531801"

DATA_FOLDER = "./_data/"
FILE_NAME = "180906LGNC_FULL"
VIDEO_FILE = DATA_FOLDER + FILE_NAME + "/" + FILE_NAME + ".mp4"
TEXT_FILE = DATA_FOLDER + FILE_NAME + "/" + FILE_NAME + ".txt"
BALL_TEXT_FILE = DATA_FOLDER + FILE_NAME + "/" + FILE_NAME + "_ball.txt"


OWL_FILE_DIRECTORY = DATA_FOLDER + "owl/"
OWL_FILE_NAME = "baseball.owl"
OWL_FILE = OWL_FILE_DIRECTORY + OWL_FILE_NAME
OWL_FILE_READONLY = OWL_FILE_DIRECTORY + "R_" + OWL_FILE_NAME
OWL_URI = "http://ailab.hanyang.ac.kr/ontology/baseball#"

FPS = 29.97
##FRAME WHICH YOU WANT TO START AFTER
START_FRAME = 126500
#START_FRAME = 14215
#START_FRAME = 19215

#START_FRAME = 38015

#START_FRAME = 39115

##YOU SHOULD CHANGE FROM HERE
FIRST_BATTERBOX_START_IN_VIDEO = 9600
FIRST_BATTERBOX_START_IN_OWL = 183013
##TO HERE

FIRST_BATTERBOX_START_IN_OWL_SECOND = int(str(FIRST_BATTERBOX_START_IN_OWL)[:2])*3600 + int(str(FIRST_BATTERBOX_START_IN_OWL)[2:4])*60 + int(str(FIRST_BATTERBOX_START_IN_OWL)[4:6])
DISTANCE_FRAME = START_FRAME - FIRST_BATTERBOX_START_IN_VIDEO
START_SECOND = int(FIRST_BATTERBOX_START_IN_OWL_SECOND + int(DISTANCE_FRAME/FPS))
START_WEB = int(str(START_SECOND//3600).zfill(2) + str((START_SECOND%3600)//60).zfill(2) + str((START_SECOND%3600)%60).zfill(2))





